# Select image from https://hub.docker.com/_/php
image: php:7.3

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null
phpunit:
  stage: test
  script:    
    - composer install
    - vendor/bin/phpunit --configuration /phpunit.xml --coverage-text 
  artifacts:
    when: always
    reports:
      junit: Tests/report.xml
