# Select image from https://hub.docker.com/_/php
image: php:7.3

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null
  # Install composer dependencies
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - php composer.phar install
phpunit:
  stage: test
  script:
    - composer install
    - vendor/bin/phpunit --configuration /phpunit.xml --log-junit report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
 
