# Select image from https://hub.docker.com/_/php
image: php:7.3

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null
phpunit:
  stage: test
  script:    
    - phpunit --configuration phpunit.xml --log-junit Tests/report.xml --coverage-text --colors=never
  coverage: \s+Lines:\s+(\d+\.\d+%)
  artifacts:
    when: always
    reports:
      junit: Tests/report.xml
 
