# Select image from https://hub.docker.com/_/php
image: php:7.3

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null

test:app:
  script:
    - phpunit --configuration phpunit.xml --coverage-text --log-junit report.xml
artifacts:
    when: always
    reports:
      junit: report.xml
