# Select image from https://hub.docker.com/_/php
image: php:7.3

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null
  - apt install wget 
phpunit:
  stage: test
  script:    
    - phpunit --configuration phpunit.xml --log-junit Tests/report.xml
  artifacts:
    when: always
    reports:
      junit: Tests/report.xml
 
